name: Hassfest Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
        with:
          path: "./custom_components/systasmartc2"
